// src/utils/constants.ts

export const COLORS = {
  primary: '#1A237E',        // Deep Indigo - header/brand
  primaryLight: '#3949AB',
  primaryDark: '#0D1347',
  accent: '#FF6F00',         // Amber - CTAs
  accentLight: '#FFA000',
  background: '#F5F7FF',
  surface: '#FFFFFF',
  surfaceAlt: '#EEF1FF',
  border: '#C5CAE9',
  borderLight: '#E8EAF6',
  text: '#1A1A2E',
  textSecondary: '#5C6BC0',
  textLight: '#9FA8DA',
  success: '#2E7D32',
  successLight: '#E8F5E9',
  error: '#C62828',
  errorLight: '#FFEBEE',
  warning: '#E65100',
  warningLight: '#FFF3E0',
  hindi: '#880E4F',          // Magenta for Hindi indicator
  english: '#1A237E',        // Indigo for English indicator
  disabled: '#B0BEC5',
  overlay: 'rgba(0,0,0,0.5)',
  toolbarBg: '#283593',
  toolbarActive: '#5C6BC0',
};

export const FONTS = {
  regular: 'Roboto-Regular',
  medium: 'Roboto-Medium',
  bold: 'Roboto-Bold',
  hindi: 'NotoSansDevanagari-Regular',
  hindiBold: 'NotoSansDevanagari-Bold',
};

export const STRINGS = {
  en: {
    appTitle: 'Document Editor',
    uploadTitle: 'Upload Document',
    uploadSubtitle: 'Select a .docx file to begin editing',
    uploadBtn: 'Choose File',
    editTitle: 'Edit Document',
    editPlaceholder: 'Start editing your document...',
    downloadBtn: 'Download as PDF',
    downloadingMsg: 'Generating PDF...',
    convertingMsg: 'Converting document...',
    successMsg: 'PDF saved successfully!',
    errorMsg: 'Something went wrong',
    changeFile: 'Change File',
    language: 'Language',
    hindi: 'हिन्दी',
    english: 'English',
    formatBold: 'Bold',
    formatItalic: 'Italic',
    formatUnderline: 'Underline',
    formatH1: 'Heading 1',
    formatH2: 'Heading 2',
    formatBullet: 'Bullet List',
    formatOrdered: 'Ordered List',
    formatAlign: 'Align',
    undo: 'Undo',
    redo: 'Redo',
    fontSize: 'Font Size',
    fontColor: 'Font Color',
    step1: 'Upload',
    step2: 'Edit',
    step3: 'Export',
    fileSizeError: 'File too large. Max 10 MB allowed.',
    fileTypeError: 'Only .docx files are supported.',
  },
  hi: {
    appTitle: 'दस्तावेज़ संपादक',
    uploadTitle: 'दस्तावेज़ अपलोड करें',
    uploadSubtitle: 'संपादन शुरू करने के लिए .docx फ़ाइल चुनें',
    uploadBtn: 'फ़ाइल चुनें',
    editTitle: 'दस्तावेज़ संपादित करें',
    editPlaceholder: 'यहाँ लिखना शुरू करें...',
    downloadBtn: 'PDF के रूप में डाउनलोड करें',
    downloadingMsg: 'PDF बनाई जा रही है...',
    convertingMsg: 'दस्तावेज़ परिवर्तित हो रहा है...',
    successMsg: 'PDF सफलतापूर्वक सहेजी गई!',
    errorMsg: 'कुछ गलत हो गया',
    changeFile: 'फ़ाइल बदलें',
    language: 'भाषा',
    hindi: 'हिन्दी',
    english: 'English',
    formatBold: 'बोल्ड',
    formatItalic: 'इटैलिक',
    formatUnderline: 'रेखांकित',
    formatH1: 'शीर्षक 1',
    formatH2: 'शीर्षक 2',
    formatBullet: 'बुलेट सूची',
    formatOrdered: 'क्रमांकित सूची',
    formatAlign: 'संरेखण',
    undo: 'पूर्ववत',
    redo: 'फिर से करें',
    fontSize: 'फ़ॉन्ट आकार',
    fontColor: 'फ़ॉन्ट रंग',
    step1: 'अपलोड',
    step2: 'संपादित करें',
    step3: 'निर्यात',
    fileSizeError: 'फ़ाइल बहुत बड़ी है। अधिकतम 10 MB अनुमत है।',
    fileTypeError: 'केवल .docx फ़ाइलें समर्थित हैं।',
  },
};

export const MAX_FILE_SIZE_MB = 10;
export const PDF_PAGE_MARGIN = 40;
